### ISSUE TITLE
Can't select template

### ISSUE THREAD

**Issue by adriadam10** [oskardotglobal/pufferpanel-docker-arm#1]
Hi, i know that this is only a repository to build the image, but i don't know if this it's fault of pufferpanel or the config from docker.
The problem is that i cannot create a new server, because i can't see the templates to select. I have scanned the http petitions, and it appears that the server is sending the info, but it does not show up on screen.

It looks like this:
![image](https://github.com/oskardotglobal/pufferpanel-docker-arm/assets/57327458/2f1009b3-b91a-4fab-a4aa-6ec50a682c3d)

I'm using the default docker-compose in addition to a reverse proxy using https with Nginx Proxy Manager with WebSockets enabled

**Comment by oskardotglobal** [comment]
Yes, this is because pufferpanel is currently being rewritten and the new version is still very unstable. If you use a version about as old as the latest package on this repository, everything *should* work fine. It's pretty clear which version is newer or older because of the design changes; if those are still there, revert further.
